#!/usr/bin/env python

import inspect
import os
import sys

ROOT = os.path.abspath(os.path.dirname(inspect.getfile(inspect.currentframe())))


sys.path.insert(0, ROOT)

import sentiment.server

sys.exit(sentiment.server.main())

